#:import Factory kivy.factory.Factory

<Zoom>:
    size_hint: 1,1


<Button1@Button>:
    background_normal: ''
    background_color: 0, 0, 0, 0
    halign: 'center'
    valign: 'bottom'
    canvas.before:
        Color:
            rgba: (.55, .55, .55, 1) if self.state == 'normal' else (0, .7, .7, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [20,]

<LabelC@Label>:
    size_hint: 0.049, 0.039
    text_size: self.size
    font_size: 15.5
    halign: 'center'
    valign: 'middle'
    color: 0,0,0,1
<TextInput>:
    write_tab: False

<STInput@TextInput>:
    background_color: 0,0,0,0.08
    padding: 15,0,0,0
<STInput2@TextInput>:
    background_color: 1,1,1,0.25
    padding: 0,8,0,0
    halign: "center"
    font_size: 20

<FinestraLogin>:
    name: FinestraLogin
    id : FinestraLogin
    GridLayout:
        cols: 1
        rows: 2

        GridLayout:
            cols: 2
            rows: 1
            Image:
                source: "Art/bgLogin/ImgLogin.jpg"
                size_hint : 0.75,1
            GridLayout:
                size_hint : 0.25,1
                cols: 1
                rows: 6
                TextInput:
                    id: inputnomepg
                    font_size: 32
                    multiline: False
                    text: ""
                Button1:
                    background_color: 1, 1, 1, 1
                    size_hint: 0.3, 0.5
                    text: "Nuovo PG"
                    color: 0,0,0,1
                    on_release: inputnomepg.text = "Nuovo PG"

                Button1:
                    background_color: 1, 1, 1, 1
                    size_hint: 0.3, 0.5
                    text: "Augustus"
                    color: 0,0,0,1
                    on_release: inputnomepg.text = "Augustus"
                Button1:
                    background_color: 1, 1, 1, 1
                    size_hint: 0.3, 0.5
                    text: "Arc"
                    color: 0,0,0,1
                    on_release: inputnomepg.text = "Arc"
                Button1:
                    background_color: 1, 1, 1, 1
                    size_hint: 0.3, 0.5
                    text: "Aldorron"
                    color: 0,0,0,1
                    on_release: inputnomepg.text = "Aldorron"
                Button1:
                    background_color: 1, 1, 1, 1
                    size_hint: 0.3, 0.5
                    text: "Sidrith"
                    color: 0,0,0,1
                    on_release: inputnomepg.text = "Sidrith"
        GridLayout:
            size_hint: 1, 0.12
            cols: 2
            rows: 1
            Button1:
                background_color: 1, 1, 1, 1
                size_hint: 0.3, 0.5
                text: "LOGIN - Master"
                color: 0,0,0,1
                on_release: root.namebutton(inputnomepg.text, master = True)
            Button1:
                background_color: 1, 1, 1, 1
                size_hint: 0.3, 0.5
                text: "LOGIN - Player"
                color: 0,0,0,1
                on_release: root.namebutton(inputnomepg.text, master = False)





<FinestraPrincipale>:

    resistenza_totkv:resistenza_totkv
    agilita_totkv:agilita_totkv
    velocita_totkv:velocita_totkv
    intelligenza_totkv:intelligenza_totkv
    concentrazione_totkv:concentrazione_totkv
    personalita_totkv:personalita_totkv
    saggezza_totkv:saggezza_totkv
    barrekv: barrekv
    boxdannokv:boxdannokv
    boxmanaspesokv:boxmanaspesokv
    boxenergiaspesakv:boxenergiaspesakv
    boxpoterespesokv:boxpoterespesokv
    labelarma:labelarma
    diario1kv:diario1kv
    diario2kv:diario2kv
    diario3kv:diario3kv
    diario4kv:diario4kv
    diario5kv:diario5kv
    diario6kv:diario6kv
    diario7kv:diario7kv
    diario8kv:diario8kv
    diario9kv:diario9kv
    diario10kv:diario10kv
    diario11kv:diario11kv
    diario12kv:diario12kv
    diario13kv:diario13kv
    diario14kv:diario14kv
    diario15kv:diario15kv
    diario16kv:diario16kv
    diario17kv:diario17kv
    diario18kv:diario18kv
    missione_1kv:missione_1kv
    missione_2kv:missione_2kv
    missione_3kv:missione_3kv
    missione_4kv:missione_4kv
    missione_5kv:missione_5kv
    missione_6kv:missione_6kv
    missione_7kv:missione_7kv
    missione_8kv:missione_8kv
    missione_reward_1kv:missione_reward_1kv
    missione_reward_2kv:missione_reward_2kv
    missione_reward_3kv:missione_reward_3kv
    missione_reward_4kv:missione_reward_4kv
    missione_reward_5kv:missione_reward_5kv
    missione_reward_6kv:missione_reward_6kv
    missione_reward_7kv:missione_reward_7kv
    missione_reward_8kv:missione_reward_8kv
    note_finestraprincipale_1kv:note_finestraprincipale_1kv
    note_finestraprincipale_2kv:note_finestraprincipale_2kv
    note_finestraprincipale_3kv:note_finestraprincipale_3kv
    note_finestraprincipale_4kv:note_finestraprincipale_4kv
    note_extrakv:note_extrakv
    appunti1kv:appunti1kv
    appunti2kv:appunti2kv
    appunti3kv:appunti3kv
    appunti4kv:appunti4kv
    appunti5kv:appunti5kv
    appunti6kv:appunti6kv
    appunti7kv:appunti7kv
    appunti8kv:appunti8kv
    appunti9kv:appunti9kv
    appunti10kv:appunti10kv
    appunti11kv:appunti11kv
    appunti12kv:appunti12kv
    appunti13kv:appunti13kv
    appunti14kv:appunti14kv
    appunti15kv:appunti15kv
    appunti16kv:appunti16kv
    appunti17kv:appunti17kv
    appunti18kv:appunti18kv
    appunti19kv:appunti19kv
    appunti20kv:appunti20kv
    appunti21kv:appunti21kv
    appunti22kv:appunti22kv
    appunti23kv:appunti23kv
    appunti24kv:appunti24kv
    appunti25kv:appunti25kv
    appunti26kv:appunti26kv
    appunti27kv:appunti27kv
    appunti28kv:appunti28kv
    appunti29kv:appunti29kv
    appunti30kv:appunti30kv
    descrizione_skill_1kv:descrizione_skill_1kv
    descrizione_skill_2kv:descrizione_skill_2kv
    descrizione_skill_3kv:descrizione_skill_3kv
    descrizione_skill_4kv:descrizione_skill_4kv
    descrizione_skill_5kv:descrizione_skill_5kv
    descrizione_skill_6kv:descrizione_skill_6kv
    descrizione_skill_7kv:descrizione_skill_7kv
    descrizione_skill_8kv:descrizione_skill_8kv
    descrizione_skill_9kv:descrizione_skill_9kv
    descrizione_skill_10kv:descrizione_skill_10kv
    descrizione_skill_11kv:descrizione_skill_11kv
    descrizione_skill_12kv:descrizione_skill_12kv
    descrizione_skill_13kv:descrizione_skill_13kv
    descrizione_skill_14kv:descrizione_skill_14kv
    descrizione_skill_15kv:descrizione_skill_15kv
    descrizione_skill_16kv:descrizione_skill_16kv
    descrizione_skill_17kv:descrizione_skill_17kv
    descrizione_skill_18kv:descrizione_skill_18kv
    descrizione_skill_19kv:descrizione_skill_19kv
    descrizione_skill_20kv:descrizione_skill_20kv
    descrizione_skill_21kv:descrizione_skill_21kv
    descrizione_skill_22kv:descrizione_skill_22kv
    descrizione_skill_23kv:descrizione_skill_23kv
    descrizione_skill_24kv:descrizione_skill_24kv
    descrizione_skill_25kv:descrizione_skill_25kv
    descrizione_skill_26kv:descrizione_skill_26kv
    descrizione_skill_27kv:descrizione_skill_27kv
    descrizione_skill_28kv:descrizione_skill_28kv
    descrizione_skill_29kv:descrizione_skill_29kv
    descrizione_skill_30kv:descrizione_skill_30kv
    descrizione_skill_31kv:descrizione_skill_31kv
    descrizione_skill_32kv:descrizione_skill_32kv
    descrizione_skill_33kv:descrizione_skill_33kv
    descrizione_skill_34kv:descrizione_skill_34kv
    descrizione_skill_35kv:descrizione_skill_35kv
    descrizione_skill_36kv:descrizione_skill_36kv
    descrizione_skill_37kv:descrizione_skill_37kv
    descrizione_skill_38kv:descrizione_skill_38kv
    descrizione_skill_39kv:descrizione_skill_39kv
    descrizione_skill_40kv:descrizione_skill_40kv
    descrizione_skill_41kv:descrizione_skill_41kv
    descrizione_skill_42kv:descrizione_skill_42kv
    descrizione_skill_43kv:descrizione_skill_43kv
    descrizione_skill_44kv:descrizione_skill_44kv
    descrizione_skill_45kv:descrizione_skill_45kv
    descrizione_skill_46kv:descrizione_skill_46kv
    descrizione_skill_47kv:descrizione_skill_47kv
    descrizione_skill_48kv:descrizione_skill_48kv
    descrizione_skill_49kv:descrizione_skill_49kv
    descrizione_skill_50kv:descrizione_skill_50kv
    descrizione_skill_51kv:descrizione_skill_51kv
    descrizione_skill_52kv:descrizione_skill_52kv
    descrizione_skill_53kv:descrizione_skill_53kv
    descrizione_skill_54kv:descrizione_skill_54kv
    descrizione_skill_55kv:descrizione_skill_55kv
    descrizione_skill_56kv:descrizione_skill_56kv
    descrizione_skill_57kv:descrizione_skill_57kv
    descrizione_skill_58kv:descrizione_skill_58kv
    descrizione_skill_59kv:descrizione_skill_59kv
    skill_sbloccatekv:skill_sbloccatekv
    faretra_1kv:faretra_1kv
    faretra_2kv:faretra_2kv
    faretra_3kv:faretra_3kv
    faretra_4kv:faretra_4kv
    faretra_5kv:faretra_5kv
    faretra_6kv:faretra_6kv
    faretra_7kv:faretra_7kv
    faretra_8kv:faretra_8kv
    faretra_9kv:faretra_9kv
    faretra_10kv:faretra_10kv
    faretra_11kv:faretra_11kv
    faretra_12kv:faretra_12kv
    faretra_13kv:faretra_13kv
    faretra_14kv:faretra_14kv
    faretra_15kv:faretra_15kv
    faretra_16kv:faretra_16kv
    faretra_17kv:faretra_17kv
    faretra_18kv:faretra_18kv
    faretra_19kv:faretra_19kv
    faretra_20kv:faretra_20kv
    faretra_21kv:faretra_21kv
    faretra_22kv:faretra_22kv
    faretra_23kv:faretra_23kv
    faretra_24kv:faretra_24kv
    faretra_25kv:faretra_25kv
    faretra_26kv:faretra_26kv
    faretra_27kv:faretra_27kv
    faretra_28kv:faretra_28kv
    faretra_29kv:faretra_29kv
    faretra_30kv:faretra_30kv
    magiaselezionata1kv:magiaselezionata1kv
    magiaselezionata2kv:magiaselezionata2kv
    slidemanaspell1kv: slidemanaspell1kv
    slidepoterespell1kv: slidepoterespell1kv
    slidemanaspell2kv: slidemanaspell2kv
    slidepoterespell2kv: slidepoterespell2kv
    boxmanaslide1: boxmanaslide1
    boxpotereslide1: boxpotereslide1
    boxpoterefree1: boxpoterefree1
    boxmanaslide2: boxmanaslide2
    boxpotereslide2: boxpotereslide2
    boxpoterefree2: boxpoterefree2
    effettospellkv1: effettospellkv1
    effettospellkv2: effettospellkv2
    magia1bottkv: magia1bottkv
    magia2bottkv: magia2bottkv
    magia3bottkv: magia3bottkv
    magia4bottkv: magia4bottkv
    magia5bottkv: magia5bottkv
    magia6bottkv: magia6bottkv
    magia7bottkv: magia7bottkv
    magia8bottkv: magia8bottkv
    magia9bottkv: magia9bottkv
    magia10bottkv: magia10bottkv
    magia11bottkv: magia11bottkv
    magia12bottkv: magia12bottkv
    magia13bottkv: magia13bottkv
    magia14bottkv: magia14bottkv
    magia15bottkv: magia15bottkv
    magia16bottkv: magia16bottkv
    magia17bottkv: magia17bottkv
    magia18bottkv: magia18bottkv
    magia19bottkv: magia19bottkv
    magia20bottkv: magia20bottkv
    magia21bottkv: magia21bottkv
    magia22bottkv: magia22bottkv
    magia23bottkv: magia23bottkv
    magia24bottkv: magia24bottkv
    magia25bottkv: magia25bottkv
    magia26bottkv: magia26bottkv
    magia27bottkv: magia27bottkv
    magia28bottkv: magia28bottkv
    magia29bottkv: magia29bottkv
    magia30bottkv: magia30bottkv
    magia31bottkv: magia31bottkv
    magia32bottkv: magia32bottkv
    magia33bottkv: magia33bottkv
    magia34bottkv: magia34bottkv
    magia35bottkv: magia35bottkv
    magia36bottkv: magia36bottkv
    magia1testokv: magia1testokv
    magia2testokv: magia2testokv
    magia3testokv: magia3testokv
    magia4testokv: magia4testokv
    magia5testokv: magia5testokv
    magia6testokv: magia6testokv
    magia7testokv: magia7testokv
    magia8testokv: magia8testokv
    magia9testokv: magia9testokv
    magia10testokv: magia10testokv
    magia11testokv: magia11testokv
    magia12testokv: magia12testokv
    magia13testokv: magia13testokv
    magia14testokv: magia14testokv
    magia15testokv: magia15testokv
    magia16testokv: magia16testokv
    magia17testokv: magia17testokv
    magia18testokv: magia18testokv
    magia19testokv: magia19testokv
    magia20testokv: magia20testokv
    magia21testokv: magia21testokv
    magia22testokv: magia22testokv
    magia23testokv: magia23testokv
    magia24testokv: magia24testokv
    magia25testokv: magia25testokv
    magia26testokv: magia26testokv
    magia27testokv: magia27testokv
    magia28testokv: magia28testokv
    magia29testokv: magia29testokv
    magia30testokv: magia30testokv
    magia31testokv: magia31testokv
    magia32testokv: magia32testokv
    magia33testokv: magia33testokv
    magia34testokv: magia34testokv
    magia35testokv: magia35testokv
    magia36testokv: magia36testokv
    barravitaNPCkv:barravitaNPCkv
    barrapa:barrapa
    barrapatext:barrapatext
    pa_usa_spell: pa_usa_spell
    pa_usa_1: pa_usa_1
    pa_usa_2: pa_usa_2
    pa_usa_3: pa_usa_3
    pa_usa_4: pa_usa_4
    pa_usa_5: pa_usa_5
    pa_usa_6: pa_usa_6
    pa_spesi: pa_spesi
    nomenpckv:nomenpckv
    exra1npckv:exra1npckv
    exra2npckv:exra2npckv
    exra3npckv:exra3npckv
    exra4npckv:exra4npckv
    exra5npckv:exra5npckv
    exra6npckv:exra6npckv
    panpckv:panpckv
    armanpckv:armanpckv
    labelattaccante:labelattaccante
    labeldifensore:labeldifensore
    boxtipodanno:boxtipodanno
    boxmodattacco:boxmodattacco
    boxdado:boxdado
    bonusdanno:bonusdanno
    boxbonustier:boxbonustier
    labeltierdanno:labeltierdanno
    campodannokv:campodannokv
    loadscreen:loadscreen
    extra1kv: extra1kv
    extra2kv: extra2kv
    extra3kv: extra3kv
    extra4kv: extra4kv
    extra5kv: extra5kv
    extra6kv: extra6kv
    extra7kv: extra7kv
    extra8kv: extra8kv
    extra9kv: extra9kv
    extra10kv: extra10kv



    Image:
        id: immaginebg
        source: "Art/bgeritrattipg/bg.png"
        size_hint : 1.3,1.3
        pos_hint : {"x": -0.15, "top" : 1.15}


    BoxLayout:
        pos_hint: {"x":0.374, "top":0.778}
        size_hint: 0.52, 0.555
        Zoom:
            id: boximgmain
            Image:
                size_hint: 1,1
                id: immaginemain
                source: 'Art/immagini/vuoto.png'
                allow_stretch: True
                pos_hint: {"x":0, "top":1}
    Image:
        id: immaginebgcut
        source: "Art/bgeritrattipg/bgcut.png"
        size_hint : 1.3,1.3
        pos_hint : {"x": -0.15, "top" : 1.15}


    Button:
        text: "Reset"
        pos_hint: {"x":0.9, "top":0.778}
        size_hint: 0.049, 0.039
        on_release: root.resetimgmain()
    Button:
        id: bottonedettagliimgmain
        text: "dettagli img"
        pos_hint: {"x":0.95, "top":0.778}
        size_hint: 0.049, 0.039
        on_release: root.mostradettagliimgmain()
    Button:
        text: "Scala\n - -"
        pos_hint: {"x":0.9, "top":0.738}
        size_hint: 0.025, 0.039
        on_release: root.imgscalamenomeno()
    Button:
        text: "Scala\n  -"
        pos_hint: {"x":0.925, "top":0.738}
        size_hint: 0.025, 0.039
        on_release: root.imgscalameno()
    Button:
        text: "Scala\n  +"
        pos_hint: {"x":0.95, "top":0.738}
        size_hint: 0.025, 0.039
        on_release: root.imgscalapiu()
    Button:
        text: "Scala\n ++"
        pos_hint: {"x":0.975, "top":0.738}
        size_hint: 0.025, 0.039
        on_release: root.imgscalapiupiu()
    Button:
        text: "su"
        pos_hint: {"x":0.933, "top":0.698}
        size_hint: 0.03, 0.039
        on_release: root.imgsu()
    Button:
        text: "giu"
        pos_hint: {"x":0.933, "top":0.618}
        size_hint: 0.03, 0.039
        on_release: root.imggiu()
    Button:
        text: "sinistra"
        pos_hint: {"x":0.908, "top":0.658}
        size_hint: 0.03, 0.039
        on_release: root.imgsinistra()
    Button:
        text: "destra"
        pos_hint: {"x":0.958, "top":0.658}
        size_hint: 0.03, 0.039
        on_release: root.imgdestra()
    Button:
        text: "ombra"
        pos_hint: {"x":0.97, "top":0.618}
        size_hint: 0.03, 0.039
        on_release: root.ombra()
    Button:
        text: "hex"
        pos_hint: {"x":0.9, "top":0.618}
        size_hint: 0.03, 0.039
        on_release: root.bottonehex()
    Button:
        text: "Vedi\nNascondi"
        pos_hint: {"x":0.9, "top":0.578}
        size_hint: 0.033, 0.039
        on_release: root.noimmaginemain()
    Button:
        text: "Griglia\nSi/No"
        pos_hint: {"x":0.933, "top":0.578}
        size_hint: 0.033, 0.039
        on_release: root.grigliasino()
    Button:
        text: "Gira"
        pos_hint: {"x":0.967, "top":0.578}
        size_hint: 0.033, 0.039
        on_release: root.giragriglia()
    Button:
        text: "XS"
        pos_hint: {"x":0.9, "top":0.538}
        size_hint: 0.02, 0.039
        on_release: root.grigliaxs()
    Button:
        text: "S"
        pos_hint: {"x":0.92, "top":0.538}
        size_hint: 0.02, 0.039
        on_release: root.griglias()
    Button:
        text: "M"
        pos_hint: {"x":0.94, "top":0.538}
        size_hint: 0.02, 0.039
        on_release: root.grigliam()
    Button:
        text: "L"
        pos_hint: {"x":0.96, "top":0.538}
        size_hint: 0.02, 0.039
        on_release: root.griglial()
    Button:
        text: "XL"
        pos_hint: {"x":0.98, "top":0.538}
        size_hint: 0.02, 0.039
        on_release: root.grigliaxl()
    BoxLayout:
        pos_hint: {"x": 4, "top": 4}
        size_hint: 0.53, 0.57
        id: boxgriglia
        Image:
            size_hint: 1,1
            id: immeginegriglia
            source: 'Art/immagini/grigliaxsmalla.png'
            allow_stretch: True
            pos_hint: {"x":0, "top":1}
    BoxLayout:
        pos_hint: {"x":0.365, "top":0.785}
        size_hint: 0.53, 0.57
        id: boxombra
        Image:
            size_hint: 1,1
            id: immegineombra
            source: 'Art/immagini/vuoto.png'
            allow_stretch: True
            pos_hint: {"x":0, "top":1}
    Button:
        id: btnreg
        size_hint: 0.05,0.09
        pos_hint: {"x":0.9, "top":0.498}
        on_release: root.aprimapperegione()
    Image:
        id: imgreg
        size_hint: 0.05,0.09
        allow_stretch: True
        source: 'Art/immagini/I-iconatamriel.png'
        pos_hint: {"x":0.9, "top":0.497}
    Button:
        id: btncit
        size_hint: 0.05,0.09
        pos_hint: {"x":0.95, "top":0.498}
        on_release: root.aprimappecitta()
    Image:
        id: imgcit
        size_hint: 0.05,0.09
        allow_stretch: True
        source: 'Art/immagini/I-iconacitta.png'
        pos_hint: {"x":0.95, "top":0.497}
    Button:
        id: btnloc
        size_hint: 0.05,0.09
        pos_hint: {"x":0.9, "top":0.408}
        on_release: root.aprimappelocale()
    Image:
        id: imgloc
        size_hint: 0.05,0.09
        allow_stretch: True
        source: 'Art/immagini/I-iconastrada.png'
        pos_hint: {"x":0.9, "top":0.407}
    Button:
        id: btnris
        size_hint: 0.05,0.09
        pos_hint: {"x":0.95, "top":0.408}
        on_release: root.aprimapperistrette()
    Image:
        id: imgris
        size_hint: 0.05,0.09
        allow_stretch: True
        source: 'Art/immagini/I-iconadungeon.png'
        pos_hint: {"x":0.95, "top":0.407}

    Button:
        id: btnnpc
        size_hint: 0.05,0.09
        pos_hint: {"x":0.9, "top":0.317}
        on_release: root.apriimgnpc()
    Image:
        id: imgnpc
        size_hint: 0.05,0.09
        allow_stretch: True
        source: 'Art/immagini/I-iconamostri.png'
        pos_hint: {"x":0.9, "top":0.318}

    TabbedPanel:
        do_default_tab: False
        tab_pos: "right_top"
        tab_width: 82
        size_hint: 0.27,0.5
        pos_hint : {"center_x": 0.135, "center_y": .255}
        background_color: 0,0,0,0
        TabbedPanelItem:
            text: "Diario"
            background_color: 0,0,0,0
            TabbedPanel:
                do_default_tab: False
                tab_pos: "left_top"
                size_hint: 1,1
                pos_hint : {"center_x": 0.115, "center_y": .255}
                TabbedPanelItem:
                    text: "Note1"
                    background_color: 0,0,0,0
                    GridLayout:
                        canvas.before:
                            Color:
                                rgba: 1, 1, 1, 1
                            Rectangle:
                                pos: self.pos
                                size: self.size
                                source: 'Art/note.png'
                        cols: 1
                        rows : 4
                        STInput:
                            id: note_finestraprincipale_1kv
                        STInput:
                            id: note_finestraprincipale_2kv
                        STInput:
                            id: note_finestraprincipale_3kv
                        STInput:
                            id: note_finestraprincipale_4kv
                TabbedPanelItem:
                    text: "Note2"
                    background_color: 0,0,0,0
                    GridLayout:
                        canvas.before:
                            Color:
                                rgba: 1, 1, 1, 1
                            Rectangle:
                                pos: self.pos
                                size: self.size
                                source: 'Art/note.png'
                        cols: 2
                        rows : 10
                        STInput:
                            size_hint: 0.7, 0.039
                            id: diario1kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: diario2kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: diario3kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: diario4kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: diario5kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: diario6kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: diario7kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: diario8kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: diario9kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: diario10kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: diario11kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: diario12kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: diario13kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: diario14kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: diario15kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: diario16kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: diario17kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: diario18kv



                TabbedPanelItem:
                    text: "Missioni"
                    background_color: 0,0,0,0
                    GridLayout:
                        canvas.before:
                            Color:
                                rgba: 1, 1, 1, 1
                            Rectangle:
                                pos: self.pos
                                size: self.size
                                source: 'Art/note.png'
                        cols: 2
                        rows : 8
                        STInput:
                            size_hint: 0.7, 0.039
                            id: missione_1kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: missione_reward_1kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: missione_2kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: missione_reward_2kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: missione_3kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: missione_reward_3kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: missione_4kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: missione_reward_4kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: missione_5kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: missione_reward_5kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: missione_6kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: missione_reward_6kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: missione_7kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: missione_reward_7kv
                        STInput:
                            size_hint: 0.7, 0.039
                            id: missione_8kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: missione_reward_8kv

                TabbedPanelItem:
                    text: "Appunti"
                    background_color: 0,0,0,0
                    GridLayout:
                        cols: 1
                        rows : 30
                        canvas.before:
                            Color:
                                rgba: 1, 1, 1, 1
                            Rectangle:
                                pos: self.pos
                                size: self.size
                                source: 'Art/note.png'
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti1kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti2kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti3kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti4kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti5kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti6kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti7kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti8kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti9kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti10kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti11kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti12kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti13kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti14kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti15kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti16kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti17kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti18kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti19kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti20kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti21kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti22kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti23kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti24kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti25kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti26kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti27kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti28kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti29kv
                        STInput:
                            size_hint: 0.3, 0.039
                            id: appunti30kv
        TabbedPanelItem:
            text: "Magie 1"
            background_color: 0,0,0,0
            FloatLayout:
                canvas.before:
                    Color:
                        rgba: 1, 1, 1, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                        source: 'Art/bgmagiev2.png'
                Label:
                    pos_hint: {"x":0.05, "top":0.99}
                    background_color: 0,0,0,0.0
                    size_hint: 0.7, 0.170
                    id: magiaselezionata1kv
                    color: 0,0,0,1
                    text: "Magia"
                    font_size: 28
                    halign:'center'
                    font_name: 'Dati\Ancient Medium'
                Slider:
                    id: slidemanaspell1kv
                    size_hint: 0.7, 0.01
                    pos_hint: {"x":0.05, "top":0.81}
                    min: 0
                    max: 150
                    step: 1
                    on_value: root.slidemanaspell1(*args)
                    Image:
                        pos: (slidemanaspell1kv.value_pos[0] - sp(16), slidemanaspell1kv.center_y - sp(16)) if slidemanaspell1kv.orientation == 'horizontal' else (slidemanaspell1kv.center_x - sp(27), slidemanaspell1kv.value_pos[1] - sp(16))
                        size_hint: None, None
                        size: sp(32), sp(32)
                        source: "Art/manaslider.png"
                Label:
                    pos_hint: {"x":0.8, "top":0.95}
                    size_hint: 0.09, 0.05
                    font_size: 19
                    text: "Effetto"
                    color: 0,0,0,1
                    background_color: 0,0,0,0.1
                Label:
                    pos_hint: {"x":0.8, "top":0.9}
                    size_hint: 0.09, 0.05
                    font_size: 19
                    id: effettospellkv1
                    color: 0,0,0,1
                    background_color: 0,0,0,1

                TextInput:
                    pos_hint: {"x":0.74, "top":0.83}
                    size_hint: 0.09, 0.05
                    font_size: 19
                    multiline: False
                    text: "0"
                    id: boxmanaslide1
                    padding: 5,2,0,0
                    background_color: 1,1,1,0.2

                Slider:
                    id: slidepoterespell1kv
                    size_hint: 0.7, 0.01
                    pos_hint: {"x":0.05, "top":0.75 }
                    min: 0
                    max: 150
                    step: 1
                    on_value: root.slidepoterespell1(*args)
                    Image:
                        pos: (slidepoterespell1kv.value_pos[0] - sp(16), slidepoterespell1kv.center_y - sp(16)) if slidepoterespell1kv.orientation == 'horizontal' else (slidepoterespell1kv.center_x - sp(27), slidepoterespell1kv.value_pos[1] - sp(16))
                        size_hint: None, None
                        size: sp(32), sp(32)
                        source: "Art/potereslider.png"

                TextInput:
                    pos_hint: {"x":0.74, "top":0.77}
                    size_hint: 0.09, 0.05
                    font_size: 19
                    multiline: False
                    text: "0"
                    id: boxpotereslide1
                    padding: 5,2,0,0
                    background_color: 1,1,1,0.2
                TextInput:
                    pos_hint: {"x":0.84, "top":0.77}
                    size_hint: 0.09, 0.05
                    font_size: 19
                    multiline: False
                    id: boxpoterefree1
                    text: "0"
                    padding: 5,2,0,0
                    background_color: 1,1,1,0.2

                Button:
                    id: magia1bottkv
                    pos_hint: {"x":0.03, "top":0.72}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(1)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia1bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia1bottkv.pos
                Label:
                    id: magia1testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":1.19}

                Button:
                    id: magia2bottkv
                    pos_hint: {"x":0.48, "top":0.72}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(2)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia2bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia2bottkv.pos
                Label:
                    id: magia2testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":1.19}

                Button:
                    id: magia3bottkv
                    pos_hint: {"x":0.03, "top":0.647}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(3)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia3bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia3bottkv.pos
                Label:
                    id: magia3testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":1.117}

                Button:
                    id: magia4bottkv
                    pos_hint: {"x":0.48, "top":0.647}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(4)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia4bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia4bottkv.pos
                Label:
                    id: magia4testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":1.117}

                Button:
                    id: magia5bottkv
                    pos_hint: {"x":0.03, "top":0.5740}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(5)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia5bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia5bottkv.pos
                Label:
                    id: magia5testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":1.044}

                Button:
                    id: magia6bottkv
                    pos_hint: {"x":0.48, "top":0.5740}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(6)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia6bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia6bottkv.pos
                Label:
                    id: magia6testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":1.044}

                Button:
                    id: magia7bottkv
                    pos_hint: {"x":0.03, "top":0.5010}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(7)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia7bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia7bottkv.pos
                Label:
                    id: magia7testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.9710}

                Button:
                    id: magia8bottkv
                    pos_hint: {"x":0.48, "top":0.5010}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(8)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia8bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia8bottkv.pos
                Label:
                    id: magia8testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.9710}

                Button:
                    id: magia9bottkv
                    pos_hint: {"x":0.03, "top":0.4280}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(9)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia9bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia9bottkv.pos
                Label:
                    id: magia9testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.8980}

                Button:
                    id: magia10bottkv
                    pos_hint: {"x":0.48, "top":0.4280}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(10)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia10bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia10bottkv.pos
                Label:
                    id: magia10testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.8980}

                Button:
                    id: magia11bottkv
                    pos_hint: {"x":0.03, "top":0.3550}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(11)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia11bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia11bottkv.pos
                Label:
                    id: magia11testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.8250}

                Button:
                    id: magia12bottkv
                    pos_hint: {"x":0.48, "top":0.3550}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(12)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia12bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia12bottkv.pos
                Label:
                    id: magia12testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.8250}

                Button:
                    id: magia13bottkv
                    pos_hint: {"x":0.03, "top":0.2820}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(13)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia13bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia13bottkv.pos
                Label:
                    id: magia13testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.7520}

                Button:
                    id: magia14bottkv
                    pos_hint: {"x":0.48, "top":0.2820}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(14)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia14bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia14bottkv.pos
                Label:
                    id: magia14testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.7520}

                Button:
                    id: magia15bottkv
                    pos_hint: {"x":0.03, "top":0.2090}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(15)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia15bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia15bottkv.pos
                Label:
                    id: magia15testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.6790}

                Button:
                    id: magia16bottkv
                    pos_hint: {"x":0.48, "top":0.2090}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(16)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia16bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia16bottkv.pos
                Label:
                    id: magia16testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.6790}

                Button:
                    id: magia17bottkv
                    pos_hint: {"x":0.03, "top":0.1360}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(17)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia17bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia17bottkv.pos
                Label:
                    id: magia17testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.6060}

                Button:
                    id: magia18bottkv
                    pos_hint: {"x":0.48, "top":0.1360}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(18)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia18bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia18bottkv.pos
                Label:
                    id: magia18testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.6060}



        TabbedPanelItem:
            text: "Magie 2"
            background_color: 0,0,0,0
            FloatLayout:
                canvas.before:
                    Color:
                        rgba: 1, 1, 1, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                        source: 'Art/bgmagiev2.png'
                Label:
                    pos_hint: {"x":0.05, "top":0.99}
                    background_color: 0,0,0,0.0
                    size_hint: 0.7, 0.170
                    id: magiaselezionata2kv
                    color: 0,0,0,1
                    text: "Magia"
                    font_size: 28
                    halign:'center'
                    font_name: 'Dati\Ancient Medium'
                Slider:
                    id: slidemanaspell2kv
                    size_hint: 0.7, 0.01
                    pos_hint: {"x":0.05, "top":0.81}
                    min: 0
                    max: 150
                    step: 1
                    on_value: root.slidemanaspell2(*args)
                    Image:
                        pos: (slidemanaspell2kv.value_pos[0] - sp(16), slidemanaspell2kv.center_y - sp(16)) if slidemanaspell2kv.orientation == 'horizontal' else (slidemanaspell2kv.center_x - sp(27), slidemanaspell2kv.value_pos[1] - sp(16))
                        size_hint: None, None
                        size: sp(32), sp(32)
                        source: "Art/manaslider.png"
                Label:
                    pos_hint: {"x":0.8, "top":0.95}
                    size_hint: 0.09, 0.05
                    font_size: 19
                    text: "Effetto"
                    color: 0,0,0,1
                    background_color: 1,1,1,0.2
                Label:
                    pos_hint: {"x":0.8, "top":0.9}
                    size_hint: 0.09, 0.05
                    font_size: 19
                    color: 0,0,0,1
                    id: effettospellkv2
                    background_color: 1,1,1,0.2
                TextInput:
                    pos_hint: {"x":0.74, "top":0.83}
                    size_hint: 0.09, 0.05
                    font_size: 19
                    multiline: False
                    id: boxmanaslide2
                    text: "0"
                    padding: 5,2,0,0
                    background_color: 1,1,1,0.2

                Slider:
                    id: slidepoterespell2kv
                    size_hint: 0.7, 0.01
                    pos_hint: {"x":0.05, "top":0.75 }
                    min: 0
                    max: 150
                    step: 1
                    on_value: root.slidepoterespell2(*args)
                    Image:
                        pos: (slidepoterespell2kv.value_pos[0] - sp(16), slidepoterespell2kv.center_y - sp(16)) if slidepoterespell2kv.orientation == 'horizontal' else (slidepoterespell2kv.center_x - sp(27), slidepoterespell2kv.value_pos[1] - sp(16))
                        size_hint: None, None
                        size: sp(32), sp(32)
                        source: "Art/potereslider.png"
                TextInput:
                    pos_hint: {"x":0.74, "top":0.77}
                    size_hint: 0.09, 0.05
                    font_size: 19
                    multiline: False
                    id: boxpotereslide2
                    text: "0"
                    padding: 5,2,0,0
                    background_color: 1,1,1,0.2
                TextInput:
                    pos_hint: {"x":0.84, "top":0.77}
                    size_hint: 0.09, 0.05
                    font_size: 19
                    multiline: False
                    id: boxpoterefree2
                    text: "0"
                    padding: 5,2,0,0
                    background_color: 1,1,1,0.2
                Button:
                    id: magia19bottkv
                    pos_hint: {"x":0.03, "top":0.72}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(19)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia19bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia19bottkv.pos
                Label:
                    id: magia19testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":1.19}

                Button:
                    id: magia20bottkv
                    pos_hint: {"x":0.48, "top":0.72}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(20)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia20bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia20bottkv.pos
                Label:
                    id: magia20testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":1.19}

                Button:
                    id: magia21bottkv
                    pos_hint: {"x":0.03, "top":0.647}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(21)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia21bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia21bottkv.pos
                Label:
                    id: magia21testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":1.117}

                Button:
                    id: magia22bottkv
                    pos_hint: {"x":0.48, "top":0.647}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(22)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia22bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia22bottkv.pos
                Label:
                    id: magia22testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":1.117}

                Button:
                    id: magia23bottkv
                    pos_hint: {"x":0.03, "top":0.5740}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(23)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia23bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia23bottkv.pos
                Label:
                    id: magia23testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":1.044}

                Button:
                    id: magia24bottkv
                    pos_hint: {"x":0.48, "top":0.5740}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(24)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia24bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia24bottkv.pos
                Label:
                    id: magia24testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":1.044}

                Button:
                    id: magia25bottkv
                    pos_hint: {"x":0.03, "top":0.5010}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(25)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia25bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia25bottkv.pos
                Label:
                    id: magia25testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.9710}

                Button:
                    id: magia26bottkv
                    pos_hint: {"x":0.48, "top":0.5010}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(26)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia26bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia26bottkv.pos
                Label:
                    id: magia26testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.9710}

                Button:
                    id: magia27bottkv
                    pos_hint: {"x":0.03, "top":0.4280}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(27)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia27bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia27bottkv.pos
                Label:
                    id: magia27testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.8980}

                Button:
                    id: magia28bottkv
                    pos_hint: {"x":0.48, "top":0.4280}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(28)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia28bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia28bottkv.pos
                Label:
                    id: magia28testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.8980}

                Button:
                    id: magia29bottkv
                    pos_hint: {"x":0.03, "top":0.3550}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(29)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia29bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia29bottkv.pos
                Label:
                    id: magia29testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.8250}

                Button:
                    id: magia30bottkv
                    pos_hint: {"x":0.48, "top":0.3550}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(30)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia30bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia30bottkv.pos
                Label:
                    id: magia30testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.8250}

                Button:
                    id: magia31bottkv
                    pos_hint: {"x":0.03, "top":0.2820}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(31)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia31bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia31bottkv.pos
                Label:
                    id: magia31testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.7520}

                Button:
                    id: magia32bottkv
                    pos_hint: {"x":0.48, "top":0.2820}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(32)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia32bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia32bottkv.pos
                Label:
                    id: magia32testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.7520}

                Button:
                    id: magia33bottkv
                    pos_hint: {"x":0.03, "top":0.2090}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(33)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia33bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia33bottkv.pos
                Label:
                    id: magia33testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.6790}

                Button:
                    id: magia34bottkv
                    pos_hint: {"x":0.48, "top":0.2090}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(34)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia34bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia34bottkv.pos
                Label:
                    id: magia34testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.6790}

                Button:
                    id: magia35bottkv
                    pos_hint: {"x":0.03, "top":0.1360}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(35)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia35bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia35bottkv.pos
                Label:
                    id: magia35testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":-0.25, "top":0.6060}

                Button:
                    id: magia36bottkv
                    pos_hint: {"x":0.48, "top":0.1360}
                    size_hint: 0.48, 0.07
                    on_release: root.selezionamagia(36)
                    background_normal: 'Art/null.png'
                    Image:
                        size: magia36bottkv.size
                        source: 'Art/Distruzioneicona.png'
                        pos: magia36bottkv.pos
                Label:
                    id: magia36testokv
                    color: 0, 0, 0, 1
                    font_size: 17.5
                    pos_hint: {"x":0.19, "top":0.6060}





        TabbedPanelItem:
            text: "Skill 1"
            background_color: 0,0,0,0
            GridLayout:
                cols: 1
                rows : 30
                canvas.before:
                    Color:
                        rgba: 1, 1, 1, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                        source: 'Art/note.png'
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_1kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_2kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_3kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_4kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_5kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_6kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_7kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_8kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_9kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_10kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_11kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_12kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_13kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_14kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_15kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_16kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_17kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_18kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_19kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_20kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_21kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_22kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_23kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_24kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_25kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_26kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_27kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_28kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_29kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_30kv
                    disabled: False

        TabbedPanelItem:
            text: "Skill 2"
            background_color: 0,0,0,0
            GridLayout:
                cols: 1
                rows : 29
                canvas.before:
                    Color:
                        rgba: 1, 1, 1, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                        source: 'Art/note.png'
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_31kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_32kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_33kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_34kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_35kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_36kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_37kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_38kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_39kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_40kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_41kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_42kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_43kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_44kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_45kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_46kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_47kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_48kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_49kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_50kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_51kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_52kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_53kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_54kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_55kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_56kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_57kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_58kv
                    disabled: False
                STInput:
                    size_hint: 0.3, 0.039
                    id: descrizione_skill_59kv
                    disabled: False

        TabbedPanelItem:
            text: "Extra/Faretra "
            background_color: 0,0,0,0
            GridLayout:
                cols: 1
                rows : 2
                canvas.before:
                    Color:
                        rgba: 1, 1, 1, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                        source: 'Art/faretra.png'
                GridLayout:
                    size_hint: 1, 0.7
                    cols: 1
                    rows : 1
                    STInput2:
                        id: skill_sbloccatekv
                GridLayout:
                    size_hint: 1, 0.3
                    cols: 10
                    rows : 3
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_1kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_2kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_3kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_4kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_5kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_6kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_7kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_8kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_9kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_10kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_11kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_12kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_13kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_14kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_15kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_16kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_17kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_18kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_19kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_20kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_21kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_22kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_23kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_24kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_25kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_26kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_27kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_28kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_29kv
                    STInput2:
                        size_hint: 0.3, 0.039
                        id: faretra_30kv
	FloatLayout:

        Button:
            size_hint: 0.049, 0.039
            pos_hint: {"x":0.1, "top":1}
            on_release: root.printer1()
        Image:
            size_hint: 0.049, 0.039
            allow_stretch: True
            source: 'Art/zainomenuicon.png'
            pos_hint: {"x":0.1, "top":1}

        Button:
            size_hint: 0.049, 0.039
            pos_hint: {"x":0.0, "top":1}
            on_release: root.nomepgopen()
        Image:
            size_hint: 0.049, 0.039
            allow_stretch: True
            source: 'Art/pgpng.png'
            pos_hint: {"x":0.0, "top":1}
        Button:
            size_hint: 0.049, 0.039
            pos_hint: {"x":0.05, "top":1}
            on_release: root.PG_NPC_open()
        Image:
            size_hint: 0.049, 0.039
            allow_stretch: True
            source: 'Art/selezionapngpng.png'
            pos_hint: {"x":0.05, "top":1}

        Button:
            size_hint: 0.049, 0.039
            pos_hint: {"x":0.15, "top":1}
            on_release: root.negozio_open()
        Image:
            size_hint: 0.049, 0.039
            allow_stretch: True
            source: 'Art/negoziopng.png'
            pos_hint: {"x":0.15, "top":1}

        Button:
            size_hint: 0.049, 0.039
            pos_hint:  {"x":0.2, "top":1}
            on_release: root.malattie_status_open()
        Image:
            size_hint: 0.049, 0.039
            allow_stretch: True
            source: 'Art/malattiestatuspng.png'
            pos_hint: {"x":0.2, "top":1}
        Button:
            size_hint: 0.049, 0.039
            pos_hint: {"x":0.25, "top":1}
            on_release: root.razze_info_open()
        Image:
            size_hint: 0.049, 0.039
            allow_stretch: True
            source: 'Art/razzepng.png'
            pos_hint: {"x":0.25, "top":1}

        Button:
            size_hint: 0.049, 0.039
            pos_hint: {"x":0.3, "top":1}
            on_release: root.meteo_info_open()
        Image:
            size_hint: 0.049, 0.039
            allow_stretch: True
            source: 'Art/meteopng.png'
            pos_hint: {"x":0.30, "top":1}
        Button:
            size_hint: 0.049, 0.039
            pos_hint: {"x":0.35, "top":1}
            on_release: root.viaggioopen()
        Image:
            size_hint: 0.049, 0.039
            allow_stretch: True
            source: 'Art/vaggiopng.png'
            pos_hint: {"x":0.35, "top":1}

        Button:
            size_hint: 0.049, 0.039
            pos_hint: {"x":0.4, "top":1}
            on_release: root.notecondivise()
        Image:
            size_hint: 0.049, 0.039
            allow_stretch: True
            source: 'Art/notecondivisepng.png'
            pos_hint: {"x":0.4, "top":1}


        Button:
            id: effettikv
            text: "Effetti"
            size_hint: 0.035,0.059
            pos_hint: {"x":0, "top":0.58}
            on_release: root.gestisci_effetti_open()
        Image:
            size_hint: 0.059, 0.059
            allow_stretch: True
            source: 'Art/effettiiconps.png'
            pos_hint: {"x":-0.012, "top":0.582}




        Image:
            size_hint: 0.08, 0.05
            allow_stretch: True
            source: 'Art/Stanchezzaiconps.png'
            pos_hint: {"x":-0.005, "top":0.95}

        Label:
            id: stanchezzakv
            color: 0.1, 0, 0, 1
            size_hint: 0.08, 0.05
            font_size: 17
            pos_hint: {"x":-0.009, "top":0.94}
        Button:
            on_release: root.stanchezzapiu()
            size_hint: 0.033, 0.05
            pos_hint: {"x":0.037, "top":0.95}
            background_color: 0,0,0,0
        Button:
            on_release: root.stanchezzameno()
            size_hint: 0.033, 0.05
            pos_hint: {"x":0.003, "top":0.95}
            background_color: 0,0,0,0
        Image:
            size_hint: 0.08, 0.05
            allow_stretch: True
            source: 'Art/ModificatoreGeneraleiconps.png'
            pos_hint: {"x":0.062, "top":0.95}
        Label:
            id: modificatore_generalekv
            color: 0.1, 0, 0, 1
            size_hint: 0.07, 0.05
            font_size: 17
            pos_hint: {"x":0.06, "top":0.94}
        Button:
            on_release: root.modgenpiu()
            size_hint: 0.033, 0.05
            pos_hint: {"x":0.102, "top":0.95}
            background_color: 0,0,0,0
        Button:
            on_release: root.modgenmeno()
            size_hint: 0.033, 0.05
            pos_hint: {"x":0.068, "top":0.95}
            background_color: 0,0,0,0
        Image:
            size_hint: 0.08, 0.05
            allow_stretch: True
            pos_hint: {"x":-0.005, "top":0.9}
            source: 'Art/Forzaiconps.png'
        Label:
            id: forza_totkv
            color: 0.1, 0.1, 0, 1
            size_hint: 0.07, 0.05
            font_size: 17
            pos_hint: {"x":-0.005, "top":0.89}

        Image:
            size_hint: 0.08, 0.05
            allow_stretch: True
            pos_hint: {"x":0.062, "top":0.9}
            source: 'Art/Resistenzaiconps.png'
        Label:
            id: resistenza_totkv
            size_hint: 0.07, 0.05
            color: 0.1, 0.1, 0, 1
            font_size: 17
            pos_hint: {"x":0.065, "top":0.89}

        Image:
            size_hint: 0.08, 0.05
            allow_stretch: True
            pos_hint: {"x":-0.005, "top":0.85}
            source: 'Art/Velocitaiconps.png'
        Label:
            id: velocita_totkv
            color: 0.1, 0.1, 0, 1
            size_hint: 0.07, 0.05
            font_size: 17
            pos_hint: {"x":-0.005, "top":0.84}

        Image:
            size_hint: 0.08, 0.05
            allow_stretch: True
            pos_hint: {"x":0.062, "top":0.85}
            source: 'Art/Agilitaiconps.png'
        Label:
            id: agilita_totkv
            size_hint: 0.07, 0.05
            color: 0.1, 0.1, 0, 1
            font_size: 17
            pos_hint: {"x":0.065, "top":0.84}

        Image:
            size_hint: 0.08, 0.05
            allow_stretch: True
            pos_hint: {"x":-0.005, "top":0.8}
            source: 'Art/Intelligenzaiconps.png'
        Label:
            id: intelligenza_totkv
            color: 0.1, 0.1, 0, 1
            size_hint: 0.07, 0.05
            font_size: 17
            pos_hint: {"x":-0.005, "top":0.79}

        Image:
            size_hint: 0.08, 0.05
            allow_stretch: True
            pos_hint: {"x":0.062, "top":0.8}
            source: 'Art/Concentrazioneiconps.png'
        Label:
            id: concentrazione_totkv
            size_hint: 0.07, 0.05
            color: 0.1, 0.1, 0, 1
            font_size: 17
            pos_hint: {"x":0.065, "top":0.79}

        Image:
            size_hint: 0.08, 0.05
            allow_stretch: True
            pos_hint: {"x":-0.005, "top":0.75}
            source: 'Art/Personalitaiconps_e.png'
        Label:
            id: personalita_totkv
            color: 0.1, 0.1, 0, 1
            size_hint: 0.07, 0.05
            font_size: 17
            pos_hint: {"x":-0.005, "top":0.74}

        Image:
            size_hint: 0.08, 0.05
            allow_stretch: True
            pos_hint: {"x":0.062, "top":0.75}
            source: 'Art/Saggezzaiconps.png'
        Label:
            id: saggezza_totkv
            size_hint: 0.07, 0.05
            color: 0.1, 0.1, 0, 1
            font_size: 17
            pos_hint: {"x":0.065, "top":0.74}


        Image:
            id: immaginepiccolapg
            size_hint: 0.23, 0.14
            allow_stretch: True
            pos_hint: {"x":0.078, "top":0.95}
            source: 'Art/bgeritrattipg/miniritrattopg.png'

        TextInput:
            id: labelarma
            background_color: 1,1,1,0.3
            text: "Bonus Tier"
            color: 0,0,0,1
            font_size: 12
            pos_hint: {"x":0.135, "top":0.81}
            size_hint:  0.115, 0.06
            padding: 5,2,0,0
        Image:
            size_hint: 0.105, 0.07
            allow_stretch: True
            pos_hint: {"x":0.1359, "top":0.762}
            source: 'Art/AttaccoeDifesaiconps.png'
        Label:
            id: attacco_totkv
            size_hint: 0.07, 0.05
            color: 0.1, 0.1, 0, 1
            font_size: 17
            pos_hint: {"x":0.122, "top":0.74}


        Label:
            id: difesa_totkv
            size_hint: 0.07, 0.05
            color: 0.1, 0.1, 0, 1
            font_size: 17
            pos_hint: {"x":0.176, "top":0.74}


        FloatLayout:
            name: "barre"
            id: barrekv
            ProgressBar:
                id: barravitakv
                min: 0
                max: 100
                value: 100
                size_hint: 0.2, 0.1
                pos_hint: {"x":0, "top":0.74}
                canvas:
                    BorderImage:
                        border: [int(min(self.width * (1) if self.max else 0, 12))]*4
                        pos: self.x, self.center_y -15.7
                        size: self.width*1.015, 31
                        source: 'Art/sfondobarrae.png'
                    BorderImage:
                        border: [int(min(self.width * (self.value/ float(self.max)) if self.max else 0, 12))] * 4
                        pos: self.x+4, self.center_y - 12
                        size: self.width * (self.value/float(self.max)) if self.max else 0, 24
                        source: 'Art/barrapf.png'



            ProgressBar:
                id: barramanakv
                min: 0
                max: 100
                value: 100
                size_hint: 0.2, 0.1
                pos_hint: {"x":0, "top":0.71}
                canvas:
                    BorderImage:
                        border: [int(min(self.width * (1) if self.max else 0, 12))]*4
                        pos: self.x, self.center_y -15.7
                        size: self.width*1.015, 31
                        source: 'Art/sfondobarrae.png'
                    BorderImage:
                        border: [int(min(self.width * (self.value/ float(self.max)) if self.max else 0, 12))] * 4
                        pos: self.x+4, self.center_y - 12
                        size: self.width * (self.value/float(self.max)) if self.max else 0, 24
                        source: 'Art/barramana.png'
            Button:
                on_release: root.sifonereset()
                id: bottonesifonekv
                size_hint: 0.05, 0.01
                color:0,0,0,1
                pos_hint: {"x":0.15, "top":0.665}
                background_color: 0,0,0,0.045



            ProgressBar:
                id: barraenkv
                min: 0
                max: 100
                value: 100
                size_hint: 0.2, 0.1
                pos_hint: {"x":0, "top":0.68}
                canvas:
                    BorderImage:
                        border: [int(min(self.width * (1) if self.max else 0, 12))]*4
                        pos: self.x, self.center_y -15.7
                        size: self.width*1.015, 31
                        source: 'Art/sfondobarrae.png'
                    BorderImage:
                        border: [int(min(self.width * (self.value/ float(self.max)) if self.max else 0, 12))] * 4
                        pos: self.x+4., self.center_y - 12
                        size: self.width * (self.value/float(self.max)) if self.max else 0, 24
                        source: 'Art/barraen.png'
            ProgressBar:
                id: barrapowkv
                min: 0
                max: 100
                value: 100
                size_hint: 0.2, 0.1
                pos_hint: {"x":0, "top":0.65}
                canvas:
                    BorderImage:
                        border: [int(min(self.width * (1) if self.max else 0, 12))]*4
                        pos: self.x, self.center_y -15.7
                        size: self.width*1.015, 31
                        source: 'Art/sfondobarrae.png'
                    BorderImage:
                        border: [int(min(self.width * (self.value/ float(self.max)) if self.max else 0, 12))] * 4
                        pos: self.x+4., self.center_y - 12
                        size: self.width * (self.value/float(self.max)) if self.max else 0, 24
                        source: 'Art/barrapotere.png'

            Button:
                on_release: root.pffull()
                text: "FULL"
                font_size: 10
                size_hint: 0.03, 0.01
                color:0,0,0,1
                pos_hint: {"x":0.0, "top":0.695}
                background_color: 0,0,0,0.1
            Button:
                on_release: root.manafull()
                text: "FULL"
                font_size: 10
                size_hint: 0.03, 0.01
                color:0,0,0,1
                pos_hint: {"x":0.0, "top":0.665}
                background_color: 0,0,0,0.1
            Button:
                on_release: root.enfull()
                text: "FULL"
                font_size: 10
                size_hint: 0.03, 0.01
                color:0,0,0,1
                pos_hint: {"x":0.0, "top":0.635}
                background_color: 0,0,0,0.1
            Button:
                on_release: root.powfull()
                text: "FULL"
                font_size: 10
                size_hint: 0.03, 0.01
                color:0,0,0,1
                pos_hint: {"x":0.0, "top":0.605}
                background_color: 0,0,0,0.1
            TextInput:
                pos_hint: {"x":0.204, "top":0.705}
                size_hint: 0.03, 0.03
                font_size: 19
                multiline: False
                id: boxdannokv
                text: "0"
                padding: 5,2,0,0
            TextInput:
                pos_hint: {"x":0.204, "top":0.675}
                size_hint: 0.03, 0.03
                multiline: False
                font_size: 19
                id: boxmanaspesokv
                text: "0"
                padding: 5,2,0,0
            TextInput:
                pos_hint: {"x":0.204, "top":0.645}
                size_hint: 0.03, 0.03
                multiline: False
                font_size: 19
                id: boxenergiaspesakv
                text: "0"
                padding: 5,2,0,0
            TextInput:
                pos_hint: {"x":0.204, "top":0.615}
                size_hint: 0.03, 0.03
                multiline: False
                font_size: 19
                id: boxpoterespesokv
                text: "0"
                padding: 5,2,0,0

            Button:
                pos_hint: {"x":0.232, "top":0.707}
                size_hint: 0.01, 0.124
                on_release: root.conferma()
                text: "C\nO\nN\nF\nE\nR\nM\nA"
                font_size: 12

            Label:
                id: textbarravitakv
                color: 0, 0, 0, 1
                size_hint: 0.2, 0.1
                pos_hint: {"x":0, "top":0.74}
            Label:
                id: textbarramanakv
                color: 0, 0, 0, 1
                size_hint: 0.2, 0.1
                pos_hint: {"x":0, "top":0.71}
            Label:
                id: textbarraenergiakv
                color: 0, 0, 0, 1
                size_hint: 0.2, 0.1
                pos_hint: {"x":0, "top":0.68}
            Label:
                id: textbarrapoterekv
                color: 0, 0, 0, 1
                size_hint: 0.2, 0.1
                pos_hint: {"x":0, "top":0.65}
    Button:
        on_release: root.tirameteo()
        text: "Tira meteo"
        size_hint: 0.1, 0.01
        pos_hint: {"x": 0.25, "top": 0.95}
        background_color:2,2,2,0.8
    Button:
        on_release: root.tempoavanza()
        size_hint: 0.1, 0.03
        pos_hint: {"x": 0.25, "top": 0.925}
        background_color:1,0,0,0
    Image:
        id: tempokv
        size_hint: 0.1, 0.035
        source: "Art/mattina.png"
        pos_hint: {"x": 0.25, "top": 0.935}
    TextInput:
        id: tempoinfokv
        pos_hint: {"x":0.25, "top":0.9}
        size_hint: 0.1, 0.17
        font_size: 12
        background_color: 1,1,1,0.3
        padding: 5,2,0,0

    Button:
        on_release: root.aggiunginotecondivise()
        text: "Aggiungi Nota"
        size_hint: 0.14, 0.01
        pos_hint: {"x": 0.35, "top": 0.95}
        background_color:2,2,2,0.8

    TextInput:
        id: notecondivisekv
        pos_hint: {"x":0.35, "top":0.935}
        size_hint: 0.14, 0.15
        font_size: 20
        background_color: 1,1,1,0.3
        padding: 5,2,0,0

    Button:
        on_release: root.colazione()
        size_hint: 0.038, 0.03
        pos_hint: {"x": 0.25, "top": 0.735}
        background_color: 0,0,0,0
    Image:
        id: colazionekv
        size_hint: 0.035, 0.035
        pos_hint: {"x": 0.25, "top": 0.735}
    Button:
        on_release: root.pranzo()
        size_hint: 0.038, 0.03
        pos_hint: {"x": 0.283, "top": 0.735}
        background_color: 1,0,0,0
    Image:
        id: pranzokv
        size_hint: 0.035, 0.035
        pos_hint: {"x": 0.283, "top": 0.735}

    Button:
        on_release: root.cena()
        size_hint: 0.038, 0.03
        pos_hint: {"x": 0.316, "top": 0.735}
        background_color: 0,0,0,0
    Image:
        id: cenakv
        size_hint: 0.035, 0.035
        pos_hint: {"x": 0.316, "top": 0.735}
    Button:
        on_release: root.skill()
        size_hint: 0.075, 0.075
        pos_hint: {"x": 0.295, "top": 0.57}
        background_color: 0,0,0,0
    Image:
        source: "Art/skillfinestra.png"
        size_hint: 0.075, 0.075
        pos_hint: {"x": 0.295, "top": 0.58}


    TextInput:
        pos_hint: {"x":0.25, "top":0.705}
        size_hint: 0.1, 0.12
        font_size: 15
        background_color: 1,1,1,0.3
        id: note_extrakv
        padding: 5,2,0,0

    CheckBox:
        group: "NPC"
        size_hint: 0.013, 0.013
        pos_hint: {"x": 0.51, "top": 0.97}
        on_active: root.selezionanpc(1)
        color: 0,0,0,1


    Button:
        id: nemico_1_bottone
        text: "NPC 1"
        on_release: root.NPCopen(1)
        size_hint: 0.05, 0.008
        pos_hint: {"x": 0.5, "top": 0.99}


    CheckBox:
        group: "NPC"
        size_hint: 0.013, 0.013
        pos_hint: {"x": 0.56, "top": 0.97}
        on_active: root.selezionanpc(2)
        color: 0,0,0,1


    Button:
        id: nemico_2_bottone
        text: "NPC 2"
        on_release: root.NPCopen(2)
        size_hint: 0.05, 0.008
        pos_hint: {"x": 0.55, "top": 0.99}


    CheckBox:
        group: "NPC"
        size_hint: 0.013, 0.013
        pos_hint: {"x": 0.61, "top": 0.97}
        on_active: root.selezionanpc(3)
        color: 0,0,0,1


    Button:
        id: nemico_3_bottone
        text: "NPC 3"
        on_release: root.NPCopen(3)
        size_hint: 0.05, 0.008
        pos_hint: {"x": 0.6, "top": 0.99}

    CheckBox:
        group: "NPC"
        size_hint: 0.013, 0.013
        pos_hint: {"x": 0.66, "top": 0.97}
        on_active: root.selezionanpc(4)
        color: 0,0,0,1


    Button:
        id: nemico_4_bottone
        text: "NPC 4"
        on_release: root.NPCopen(4)
        size_hint: 0.05, 0.008
        pos_hint: {"x": 0.65, "top": 0.99}

    CheckBox:
        group: "NPC"
        size_hint: 0.013, 0.013
        pos_hint: {"x": 0.71, "top": 0.97}
        on_active: root.selezionanpc(5)
        color: 0,0,0,1


    Button:
        id: nemico_5_bottone
        text: "NPC 5"
        on_release: root.NPCopen(5)
        size_hint: 0.05, 0.008
        pos_hint: {"x": 0.7, "top": 0.99}


    CheckBox:
        group: "NPC"
        size_hint: 0.013, 0.013
        pos_hint: {"x": 0.76, "top": 0.97}
        on_active: root.selezionanpc(6)
        color: 0,0,0,1


    Button:
        id: nemico_6_bottone
        text: "NPC 6"
        on_release: root.NPCopen(6)
        size_hint: 0.05, 0.008
        pos_hint: {"x": 0.75, "top": 0.99}


    CheckBox:
        group: "NPC"
        size_hint: 0.013, 0.013
        pos_hint: {"x": 0.81, "top": 0.97}
        on_active: root.selezionanpc(7)
        color: 0,0,0,1


    Button:
        id: nemico_7_bottone
        text: "NPC 7"
        on_release: root.NPCopen(7)
        size_hint: 0.05, 0.008
        pos_hint: {"x": 0.8, "top": 0.99}

    CheckBox:
        group: "NPC"
        size_hint: 0.013, 0.013
        pos_hint: {"x": 0.86, "top": 0.97}
        on_active: root.selezionanpc(8)
        color: 0,0,0,1


    Button:
        id: nemico_8_bottone
        text: "NPC 8"
        on_release: root.NPCopen(8)
        size_hint: 0.05, 0.008
        pos_hint: {"x": 0.85, "top": 0.99}

    CheckBox:
        group: "NPC"
        size_hint: 0.013, 0.013
        pos_hint: {"x": 0.91, "top": 0.97}
        on_active: root.selezionanpc(9)
        color: 0,0,0,1


    Button:
        id: nemico_9_bottone
        text: "NPC 9"
        on_release: root.NPCopen(9)
        size_hint: 0.05, 0.008
        pos_hint: {"x": 0.9, "top": 0.99}

    CheckBox:
        group: "NPC"
        size_hint: 0.013, 0.013
        pos_hint: {"x": 0.96, "top": 0.97}
        on_active: root.selezionanpc(10)
        color: 0,0,0,1



    Button:
        id: nemico_10_bottone
        text: "NPC 10"
        on_release: root.NPCopen(10)
        size_hint: 0.05, 0.008
        pos_hint: {"x": 0.95, "top": 0.99}



    ProgressBar:
        id: barravitaNPCkv
        min: 0
        max: 100
        value: 0
        size_hint: 0.195, 0.02
        pos_hint: {"x":0.5, "top":0.93}
        canvas:
            BorderImage:
                border: [int(min(self.width * (self.value/ float(self.max)) if self.max else 0, 12))] * 4
                pos: self.x+4, self.center_y
                size: self.width * (self.value/float(self.max)) if self.max else 0, 24
                source: 'Art/barrapf.png'



    Image:
        size_hint: 0.2, 0.2
        allow_stretch: True
        source: 'Art/barravitanemicobg.png'
        pos_hint: {"x":0.5, "top":1.03}

    Label:
        pos_hint: {"x":0.7, "top":0.95}
        size_hint: 0.1, 0.039
        id: nomenpckv
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.7)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [0,]
    Label:
        pos_hint: {"x":0.8, "top":0.95}
        size_hint: 0.1, 0.039
        id: armanpckv
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.7)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [0,]

    Label:
        pos_hint: {"x":0.9, "top":0.95}
        size_hint: 0.1, 0.039
        id: panpckv
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.7)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [0,]
    Label:
        pos_hint: {"x":0.5, "top":0.911}
        size_hint: 0.25, 0.039
        id: exra1npckv
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.7)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [0,]
    Label:
        pos_hint: {"x":0.75, "top":0.911}
        size_hint: 0.25, 0.039
        id: exra2npckv
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.7)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [0,]
    Label:
        pos_hint: {"x":0.5, "top":0.871}
        size_hint: 0.25, 0.039
        id: exra3npckv
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.7)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [0,]
    Label:
        pos_hint: {"x":0.75, "top":0.871}
        size_hint: 0.25, 0.039
        id: exra4npckv
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.7)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [0,]
    Label:
        pos_hint: {"x":0.5, "top":0.831}
        size_hint: 0.25, 0.039
        id: exra5npckv
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.7)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [0,]
    Label:
        pos_hint: {"x":0.75, "top":0.831}
        size_hint: 0.25, 0.039
        id: exra6npckv
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.7)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [0,]
    ProgressBar:
        id: barrapa
        min: 0
        max: 1
        value: 1
        size_hint: 0.08, 0.02
        pos_hint: {"x":0.27, "top":0.5}
        canvas:
            BorderImage:
                border: [int(min(self.width * (1) if self.max else 0, 12))]*4
                pos: self.x, self.center_y -15.7
                size: self.width*1.05, 31
                source: 'Art/sfondobarrae.png'
            BorderImage:
                border: [int(min(self.width * (self.value/ float(self.max)) if self.max else 0, 12))] * 4
                pos: self.x+4, self.center_y -12
                size: self.width * (self.value/float(self.max)) if self.max else 0, 22
                source: 'Art/barrapa.png'

    Label:
        id:barrapatext
        pos_hint: {"x":0.27 , "top":0.5}
        size_hint: 0.08, 0.02
    Button:
        pos_hint: {"x":0.27 , "top":0.505}
        size_hint: 0.085,0.03
        background_color:(0,0,0,0)
        on_release: root.pareset()

    TextInput:
        halign: 'center'
        padding: 2, 7, 2, 7
        id: pa_usa_1
        text: "0"
        pos_hint: {"x":0.27, "top":0.47}
        size_hint: 0.019, 0.035
        font_size: 20
    TextInput:
        halign: 'center'
        padding: 2, 7, 2, 7
        id: pa_usa_2
        text: "0"
        pos_hint: {"x":0.29, "top":0.47}
        size_hint: 0.019, 0.035
        font_size: 20
    TextInput:
        halign: 'center'
        padding: 2, 7, 2, 7
        id: pa_usa_3
        text: "0"
        pos_hint: {"x":0.31, "top":0.47}
        size_hint: 0.019, 0.035
        font_size: 20
    TextInput:
        halign: 'center'
        padding: 2, 7, 2, 7
        id: pa_usa_4
        text: "0"
        pos_hint: {"x":0.33, "top":0.47}
        size_hint: 0.019, 0.035
        font_size: 20
    TextInput:
        halign: 'center'
        padding: 2, 7, 2, 7
        id: pa_usa_5
        text: "0"
        pos_hint: {"x":0.27, "top":0.433}
        size_hint: 0.019, 0.035
        font_size: 20
    TextInput:
        halign: 'center'
        padding: 2, 7, 2, 7
        id: pa_usa_6
        text: "0"
        pos_hint: {"x":0.29, "top":0.433}
        size_hint: 0.019, 0.035
        font_size: 20
    TextInput:
        halign: 'center'
        padding: 2, 7, 2, 7
        id: pa_usa_spell
        text: "0"
        pos_hint: {"x":0.31, "top":0.433}
        size_hint: 0.019, 0.035
        font_size: 20
        disabled: True
    Button:
        halign: 'center'
        id: pa_spesi
        text: "0"
        on_release: root.barrapab()
        pos_hint: {"x":0.33, "top":0.433}
        size_hint: 0.019, 0.035
        font_size: 20

    Button:
        text: "PG"
        pos_hint: {"x":0.27, "top":0.397}
        size_hint: 0.02, 0.03
        on_release: root.selezionacombattente(0)
    Button:
        text: "1"
        pos_hint: {"x":0.29, "top":0.397}
        size_hint: 0.02, 0.03
        on_release: root.selezionacombattente(1)
    Button:
        text: "2"
        pos_hint: {"x":0.31, "top":0.397}
        size_hint: 0.02, 0.03
        on_release: root.selezionacombattente(2)
    Button:
        text: "3"
        pos_hint: {"x":0.33, "top":0.397}
        size_hint: 0.02, 0.03
        on_release: root.selezionacombattente(3)
    Button:
        text: "4"
        pos_hint: {"x":0.27, "top":0.368}
        size_hint: 0.02, 0.03
        on_release: root.selezionacombattente(4)
    Button:
        text: "5"
        pos_hint: {"x":0.29, "top":0.368}
        size_hint: 0.02, 0.03
        on_release: root.selezionacombattente(5)
    Button:
        text: "6"
        pos_hint: {"x":0.31, "top":0.368}
        size_hint: 0.02, 0.03
        on_release: root.selezionacombattente(6)
    Button:
        text: "7"
        pos_hint: {"x":0.33, "top":0.368}
        size_hint: 0.02, 0.03
        on_release: root.selezionacombattente(7)
    Button:
        text: "8"
        pos_hint: {"x":0.27, "top":0.339}
        size_hint: 0.02, 0.03
        on_release: root.selezionacombattente(8)
    Button:
        text: "9"
        pos_hint: {"x":0.29, "top":0.339}
        size_hint: 0.02, 0.03
        on_release: root.selezionacombattente(9)
    Button:
        text: "10"
        pos_hint: {"x":0.31, "top":0.339}
        size_hint: 0.02, 0.03
        on_release: root.selezionacombattente(10)
    Button:
        text: "INV"
        pos_hint: {"x":0.33, "top":0.339}
        size_hint: 0.02, 0.03
        on_release: root.invertiattaccante()

    Label:
        id: labelattaccante
        text: "A"
        pos_hint: {"x":0.27, "top":0.31}
        size_hint: 0.0275, 0.03
        background_color: 0, 0, 0, 0
        canvas.before:
            Color:
                rgba: (1, 0.2, 0.2, 0.8)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [20,]

    Label:
        text: "VS"
        pos_hint: {"x":0.2975, "top":0.31}
        size_hint: 0.0275, 0.03
        color: 0, 0, 0, 1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 0.8)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [0,]
    Label:
        id: labeldifensore
        text: "b"
        pos_hint: {"x":0.3250, "top":0.31}
        size_hint: 0.0275, 0.03
        background_color: 0, 0, 0, 0
        canvas.before:
            Color:
                rgba: (0.8, 0.7, 0, 0.8)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [20,]
    Button:
        text: "Cont."
        pos_hint: {"x":0.27, "top":0.28}
        size_hint: 0.0275, 0.03
        on_release: boxtipodanno.text = "Contundente"

    Button:
        text: "Tagl."
        pos_hint: {"x":0.2975, "top":0.28}
        size_hint: 0.0275, 0.03
        on_release: boxtipodanno.text = "Taglio"

    Button:
        text: "Perf."
        pos_hint: {"x":0.3250, "top":0.28}
        size_hint: 0.0275, 0.03
        on_release: boxtipodanno.text = "Perforante"

    Label:
        id: boxtipodanno
        pos_hint: {"x":0.27, "top":0.25}
        size_hint: 0.08, 0.03
        halign: 'center'
        font_size: 20
        color:0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1)
            Rectangle:
                pos: self.pos
                size: self.size

    Button:
        text: "For"
        id: boxatk0
        pos_hint: {"x":0.27, "top":0.222}
        size_hint: 0.02, 0.02
        background_color: 0,0,0,1
        on_release: root.selezionacarattattacco(0)
    Button:
        text: "Res"
        id:boxatk1
        pos_hint: {"x":0.29, "top":0.222}
        size_hint: 0.02, 0.02
        background_color: 0,0,0,1
        on_release: root.selezionacarattattacco(1)
    Button:
        text: "Vel"
        id:boxatk2
        pos_hint: {"x":0.31, "top":0.222}
        size_hint: 0.02, 0.02
        background_color: 0,0,0,1
        on_release: root.selezionacarattattacco(2)
    Button:
        text: "Agi"
        id:boxatk3
        pos_hint: {"x":0.33, "top":0.222}
        size_hint: 0.02, 0.02
        background_color: 0,0,0,1
        on_release: root.selezionacarattattacco(3)
    Button:
        text: "Int"
        id: boxatk4
        pos_hint: {"x":0.27, "top":0.202}
        size_hint: 0.02, 0.02
        background_color: 0,0,0,1
        on_release: root.selezionacarattattacco(4)

    Button:
        text: "Con"
        id: boxatk5
        pos_hint: {"x":0.29, "top":0.202}
        size_hint: 0.02, 0.02
        background_color: 0,0,0,1
        on_release: root.selezionacarattattacco(5)
    Button:
        text: "Per"
        id: boxatk6
        pos_hint: {"x":0.31, "top":0.202}
        size_hint: 0.02, 0.02
        background_color: 0,0,0,1
        on_release: root.selezionacarattattacco(6)
    Button:
        text: "Sag"
        id: boxatk7
        pos_hint: {"x":0.33, "top":0.202}
        size_hint: 0.02, 0.02
        background_color: 0,0,0,1
        on_release: root.selezionacarattattacco(7)

    Label:
        background_color: 0,0,0,1
        text: "+Atk."
        color: 0,0,0,1
        font_size: 15
        pos_hint: {"x":0.27, "top":0.182}
        size_hint: 0.02, 0.02
    TextInput:
        id: boxmodattacco
        pos_hint: {"x":0.27, "top":0.167}
        size_hint: 0.02, 0.03
        font_size: 23
        text: "0"
        padding: 8, 1, 1, 1
    Label:
        background_color: 0,0,0,1
        text: "Dado"
        color: 0,0,0,1
        font_size: 15
        pos_hint: {"x":0.29, "top":0.182}
        size_hint: 0.02, 0.02

    TextInput:
        id: boxdado
        pos_hint: {"x":0.29, "top":0.167}
        size_hint: 0.02, 0.03
        font_size: 23
        text: "0"
        padding: 8, 1, 1, 1
    Label:
        background_color: 0,0,0,1
        text: "+Tier"
        color: 0,0,0,1
        font_size: 15
        pos_hint: {"x":0.31, "top":0.182}
        size_hint: 0.02, 0.02

    TextInput:
        id: boxbonustier
        pos_hint: {"x":0.31, "top":0.167}
        size_hint: 0.02, 0.03
        font_size: 23
        text: "0"
        padding: 8, 1, 1, 1
    Label:
        background_color: 0,0,0,1
        text: "+DMG"
        color: 0,0,0,1
        font_size: 15
        pos_hint: {"x":0.33, "top":0.182}
        size_hint: 0.02, 0.02
    TextInput:
        id: bonusdanno
        pos_hint: {"x":0.33, "top":0.167}
        size_hint: 0.02, 0.03
        font_size: 23
        text: "0"
        padding: 8, 1, 1, 1

    Button1:
        text: "ATTACCA"
        on_release: root.attaccanemico()
        pos_hint: {"x":0.27, "top":0.137}
        size_hint: 0.08, 0.03
        canvas.before:
            Color:
                rgba: (1, 0.5, 0.5, 1) if self.state == 'normal' else (0, .7, .7, 1)
            Rectangle:
                pos: self.pos
                size: self.size
    Label:
        id: labeltierdanno
        pos_hint: {"x":0.27, "top":0.1055}
        size_hint: 0.06, 0.045
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1)
            Rectangle:
                pos: self.pos
                size: self.size
    Button1:
        text: "TIRA"
        on_release: root.tiradadiattacco()
        pos_hint: {"x":0.33, "top":0.1055}
        size_hint: 0.02, 0.045
        canvas.before:
            Color:
                rgba: (1, 0.3, 0.3, 1) if self.state == 'normal' else (0, .7, .7, 1)
            Rectangle:
                pos: self.pos
                size: self.size
    TextInput:
        id: campodannokv
        pos_hint: {"x":0.27, "top":0.062}
        size_hint: 0.06, 0.03
        text: "0"
        font_size: 15
        padding: 8, 1, 1, 1

    Button1:
        text: "Fisico"
        on_release: root.dannofisico()
        size_hint: 0.02, 0.03
        pos_hint: {"x":0.33, "top":0.062}
        color: 0,0,0,1
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size

    Button1:
        text: "Fuoco"
        on_release: root.dannoelementale("fuoco")
        size_hint: 0.02, 0.03
        pos_hint: {"x":0.27, "top":0.032}
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 0, 0, 1) if self.state == 'normal' else (0, .7, .7, 1)
            Rectangle:
                pos: self.pos
                size: self.size
    Button1:
        text: "Gelo"
        on_release: root.dannoelementale("gelo")
        size_hint: 0.02, 0.03
        pos_hint: {"x":0.29, "top":0.032}
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (0.5, 0.5, 1, 1) if self.state == 'normal' else (0, .7, .7, 1)
            Rectangle:
                pos: self.pos
                size: self.size
    Button1:
        text: "Elettro"
        on_release: root.dannoelementale("elettro")
        size_hint: 0.02, 0.03
        pos_hint: {"x":0.31, "top":0.032}
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: (1, 1, 0.5, 1) if self.state == 'normal' else (0, .7, .7, 1)
            Rectangle:
                pos: self.pos
                size: self.size
    Button1:
        text: "Puro"
        on_release: root.dannopuro()
        color: 0,0,0,1
        size_hint: 0.02, 0.03
        pos_hint: {"x":0.33, "top":0.032}
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1) if self.state == 'normal' else (0, .7, .7, 1)
            Rectangle:
                pos: self.pos
                size: self.size



    TextInput:
        id: extra1kv
        pos_hint: {"x":0.36, "top":0.21}
        size_hint: 0.12, 0.1
        font_size: 20
        text: "0"
        padding: 8, 1, 1, 1
        background_color: 1,1,1,0.4
    TextInput:
        id: extra2kv
        pos_hint: {"x":0.48, "top":0.21}
        size_hint: 0.12, 0.1
        font_size: 20
        text: "0"
        padding: 8, 1, 1, 1
        background_color: 1,1,1,0.4
    TextInput:
        id: extra3kv
        pos_hint: {"x":0.6, "top":0.21}
        size_hint: 0.12, 0.1
        font_size: 20
        text: "0"
        padding: 8, 1, 1, 1
        background_color: 1,1,1,0.4
    TextInput:
        id: extra4kv
        pos_hint: {"x":0.72, "top":0.21}
        size_hint: 0.12, 0.1
        font_size: 20
        text: "0"
        padding: 8, 1, 1, 1
        background_color: 1,1,1,0.4
    TextInput:
        id: extra5kv
        pos_hint: {"x":0.84, "top":0.21}
        size_hint: 0.12, 0.1
        font_size: 20
        text: "0"
        padding: 8, 1, 1, 1
        background_color: 1,1,1,0.4
    TextInput:
        id: extra6kv
        pos_hint: {"x":0.36, "top":0.1}
        size_hint: 0.12, 0.1
        font_size: 20
        text: "0"
        padding: 8, 1, 1, 1
        background_color: 1,1,1,0.4
    TextInput:
        id: extra7kv
        pos_hint: {"x":0.48, "top":0.1}
        size_hint: 0.12, 0.1
        font_size: 20
        text: "0"
        padding: 8, 1, 1, 1
        background_color: 1,1,1,0.4
    TextInput:
        id: extra8kv
        pos_hint: {"x":0.6, "top":0.1}
        size_hint: 0.12, 0.1
        font_size: 20
        text: "0"
        padding: 8, 1, 1, 1
        background_color: 1,1,1,0.4
    TextInput:
        id: extra9kv
        pos_hint: {"x":0.72, "top":0.1}
        size_hint: 0.12, 0.1
        font_size: 20
        text: "0"
        padding: 8, 1, 1, 1
        background_color: 1,1,1,0.4
    TextInput:
        id: extra10kv
        pos_hint: {"x":0.84, "top":0.1}
        size_hint: 0.12, 0.1
        font_size: 20
        text: "0"
        padding: 8, 1, 1, 1
        background_color: 1,1,1,0.4



    Image:
        id: critminimgkv
        size_hint: 0.0, 0.0
        allow_stretch: True
        source: 'Art/immagini/highwall.jpg'
        pos_hint: {"x":0.3, "top":0.7}
        source: 'Art/critmin.png'
    Image:
        id: critnorimgkv
        size_hint: 0.0, 0.0
        allow_stretch: True
        source: 'Art/critnor.png'
        pos_hint: {"x":0.25, "top":0.8}


    Image:
        id: critmagimgkv
        size_hint: 0.0, 0.0
        allow_stretch: True
        source: 'Art/critmag.png'
        pos_hint: {"x":0.1, "top":0.9}

    Image:
        id: loadscreen
        source: "Art/loadscreen.png"
        size_hint : 1.3,1.3
        pos_hint : {"x": -0.15, "top" : 1.15}
